const appDataLists = {
    "loanPurposeList1" : [
        { key: "Select", text: "Select", label: "Select a loan purpose", plKey: "ALL" },
        { key: "Debt Consolidation", text: "Debt Consolidation", label: "Debt Consolidation", plKey: "CONSOLIDATE_DEBT" },
        { key: "Credit Card Refinancing", text: "Credit Card Refinancing", label: "Credit Card Refinancing", plKey: "REFINANCE_CREDIT_CARD" },
        { key: "Vacation", text: "Vacation", label: "Vacation", plKey: "VACATION" },
        { key: "Moving", text: "Moving", label: "Moving", plKey: "MOVING" },
        { key: "Auto Expense", text: "Auto Expense", label: "Auto Expense", plKey: "AUTO_EXPENSE" },
        { key: "Medical Expense", text: "Medical Expense", label: "Medical Expense", plKey: "MEDICAL_EXPENSE" },
        { key: "Education Expense", text: "Education Expense", label: "Education Expense", plKey: "EDUCATION_EXPENSE" },
        { key: "Business Funding", text: "Business Funding", label: "Business Funding", plKey: "BUSINESS" },
        { key: "Wedding", text: "Wedding", label: "Wedding", plKey: "WEDDING" },
        { key: "Home Improvement", text: "Home Improvement", label: "Home Improvement", plKey: "HOME_IMPROVEMENT" },
        { key: "Other", text: "Other", label: "Other", plKey: "OTHER" }
    ],
    "stateList": [
        { key: "Select", text: "Select State", label: "Select State" },
        {key: "Alabama", text: "Alabama", label : "Alabama"},
        {key: "Alaska", text: "Alaska", label: "Alaska"},
        {key: "American Samoa",text: "American Samoa",label: "American Samoa"},
        {key: "Arizona",text: "Arizona",label: "Arizona"},
        {key: "Arkansas",text: "Arkansas",label: "Arkansas"},
        {key: "California",text: "California",label: "California"},
        {key: "Colorado",text: "Colorado",label: "Colorado"},
        {key: "Connecticut",text: "Connecticut",label: "Connecticut"},
        {key: "Delaware",text: "Delaware",label: "Delaware"},
        {key: "District Of Columbia",text: "District Of Columbia",label: "District Of Columbia"},
        {key: "Florida",text: "Florida",label: "Florida"},
        {key: "Georgia",text: "Georgia",label: "Georgia"},
        {key: "Guam",text: "Guam",label: "Guam"},
        {key: "Hawaii",text: "Hawaii",label: "Hawaii"},
        {key: "Idaho",text: "Idaho",label: "Idaho"},
        {key: "Illinois",text: "Illinois",label: "Illinois"},
        {key: "Indiana",text: "Indiana",label: "Indiana"},
        {key: "Iowa",text: "Iowa",label: "Iowa"},
        {key: "Kansas",text: "Kansas",label: "Kansas"},
        {key: "Kentucky",text: "Kentucky",label: "Kentucky"},
        {key: "Louisiana",text: "Louisiana",label: "Louisiana"},
        {key: "Maine",text: "Maine",label: "Maine"},
        {key: "Marshall Islands",text: "Marshall Islands",label: "Marshall Islands"},
        {key: "Maryland",text: "Maryland",label: "Maryland"},
        {key: "Massachusetts",text: "Massachusetts",label: "Massachusetts"},
        {key: "Michigan",text: "Michigan",label: "Michigan"},
        {key: "Minnesota",text: "Minnesota",label: "Minnesota"},
        {key: "Mississippi",text: "Mississippi",label: "Mississippi"},
        {key: "Missouri",text: "Missouri",label: "Missouri"},
        {key: "Montana",text: "Montana",label: "Montana"},
        {key: "Nebraska",text: "Nebraska",label: "Nebraska"},
        {key: "Nevada",text: "Nevada",label: "Nevada"},
        {key: "New Hampshire",text: "New Hampshire",label: "New Hampshire"},
        {key: "New Jersey",text: "New Jersey",label: "New Jersey"},
        {key: "New Mexico",text: "New Mexico",label: "New Mexico"},
        {key: "New York",text: "New York",label: "New York"},
        {key: "North Carolina",text: "North Carolina",label: "North Carolina"},
        {key: "North Dakota",text: "North Dakota",label: "North Dakota"},
        {key: "Ohio",text: "Ohio",label: "Ohio"},
        {key: "Oklahoma",text: "Oklahoma",label: "Oklahoma"},
        {key: "Oregon",text: "Oregon",label: "Oregon"},
        {key: "Palau",text: "Palau",label: "Palau"},
        {key: "Pennsylvania",text: "Pennsylvania",label: "Pennsylvania"},
        {key: "Puerto Rico",text: "Puerto Rico",label: "Puerto Rico"},
        {key: "Rhode Island",text: "Rhode Island",label: "Rhode Island"},
        {key: "South Carolina",text: "South Carolina",label: "South Carolina"},
        {key: "South Dakota",text: "South Dakota",label: "South Dakota"},
        {key: "Tennessee",text: "Tennessee",label: "Tennessee"},
        {key: "Texas",text: "Texas",label: "Texas"},
        {key: "Utah",text: "Utah",label: "Utah"},
        {key: "Vermont",text: "Vermont",label: "Vermont"},
        {key: "Virgin Islands",text: "Virgin Islands",label: "Virgin Islands"},
        {key: "Virginia",text: "Virginia",label: "Virginia"},
        {key: "Washington",text: "Washington",label: "Washington"},
        {key: "West Virginia",text: "West Virginia",label: "West Virginia"},
        {key: "Wisconsin",text: "Wisconsin",label: "Wisconsin"},
        {key: "Wyoming",text: "Wyoming",label: "Wyoming"}
    ],
    "housingList": [
        { key: "OWN_WITH_MORTGAGE", text: "Own – with mortgage", label: "Own – with mortgage", tabIndex:"1" },
        { key: "OWN_NO_MORTGAGE", text: "Own – no mortgage", label: "Own – no mortgage", tabIndex:"2" },
        { key: "RENT", text: "Rent", label: "Rent", tabIndex:"3" },
        { key: "LIVING_RENT_FREE", text: "Living rent free", label: "Living rent free", tabIndex:"4" }
    ],
    "estimatedCreditScoreList":[
        { key: "720-850", text: "Excellent (720-850)", label: "Excellent (720-850)", tabIndex:"1" },
        { key: "680-719", text: "Good (680-719)", label: "Good (680-719)", tabIndex:"2" },
        { key: "620-679", text: "Average (620-679)", label: "Average (620-679)", tabIndex:"3" },
        { key: "350-619", text: "Poor (below 620)", label: "Poor (below 620)", tabIndex:"4" },
    ],
    "employmentList":[
        { key: "FULL_TIME", text: "Full Time", label: "Full Time", tabIndex:"1" },
        { key: "PART_TIME", text: "Part Time", label: "Part Time", tabIndex:"2" },
        { key: "SELF_EMPLOYED", text: "Self Employed", label: "Self Employed", tabIndex:"3" },
        { key: "RETIRED", text: "Retired", label: "Retired", tabIndex:"4" },
        { key: "STUDENT", text: "Student", label: "Student", tabIndex:"5" },
        { key: "UNEMPLOYED", text: "Unemployed", label: "Unemployed", tabIndex:"6" },
        { key: "OTHER", text: "Other Income", label: "Other Income", tabIndex:"7" }
    ],
    "AddCoborrower":[
        { key: "Yes", text: "Yes", label: "Yes", tabIndex:"1" },
        { key: "No, Continue", text: "No, Continue", label: "No, Continue", tabIndex:"2" }
    ]
};
export default appDataLists;